apiVersion: batch/v1
kind: CronJob
metadata:
  name: loki-to-parquet-infra
spec:
  schedule: "1-59/5 * * * *"   # every 5m, offset
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: loki-extractor
          restartPolicy: Never
          containers:
            - name: extractor
              image: quay.io/YOUR_NS/loki-to-parquet:0.1
              imagePullPolicy: IfNotPresent
              env:
                - name: LOKI_URL
                  value: "https://logging-loki-openshift-logging.apps.logging.ocp-poc-demo.com"
                - name: LOKI_TENANT
                  value: "infrastructure"
                - name: LOKI_BEARER
                  value: "<PUT_YOUR_BEARER_TOKEN_HERE>"
                - name: VERIFY_TLS
                  value: "false"   # you used curl -k; flip to true when CA is in image
                - name: WINDOW_MIN
                  value: "5"
                - name: LOKI_STEP
                  value: "30s"
                - name: S3_ENDPOINT
                  value: "http://192.168.4.152:9000"
                - name: S3_BUCKET
                  value: "rhoai-observ-model"
                # Partition by tenant in the prefix
                - name: S3_PREFIX
                  value: "loki/parquet/log_type=infrastructure"
                # If your script reads AWS_* from env (recommended):
                - name: AWS_ACCESS_KEY_ID
                  value: "<KEY>"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "<SECRET>"
                - name: QUERIES_PATH
                  value: "/etc/loki-extractor/queries.yaml"
              volumeMounts:
                - name: queries
                  mountPath: /etc/loki-extractor/queries.yaml
                  subPath: queries.yaml
                  readOnly: true
          volumes:
            - name: queries
              configMap:
                name: loki-extractor-queries-infra
