apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-extractor-queries-app
data:
  queries.yaml: |
    queries:
      - name: app_5xx
        logql: '{log_type="application", status=~"5.."} | json'
        limit: 10000
      - name: app_slow
        logql: '{log_type="application"} |= "timeout"'
        limit: 10000
